export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';
export const LOGIN_ERROR = 'LOGIN_ERROR';


export const SET_AUTHORIZED_USER = 'SET_AUTHORIZED_USER';
